### ISSUE TITLE
视频怎么是黑白的

### ISSUE THREAD

**Issue by chancier** [yegail/SGPlayer-iOS#1]
@yegail

**Comment by yegail** [comment]
加了一个黑白滤镜

**Comment by yegail** [comment]
// 开启黑灰滤镜
self.player.hasGrayFilter = YES;
改为NO就是正常的了

**Comment by chancier** [comment]
> // 开启黑灰滤镜
> self.player.hasGrayFilter = YES;
> 改为NO就是正常的了

VR用什么渲染的呢，能手势拖动之后一键归位吗

**Comment by yegail** [comment]
OpenGLES渲染的，具体请看项目https://github.com/libobjc/SGPlayer，我是fork的这个
